<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQXD6qSV\App_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQXD6qSV/App_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/ContainerQXD6qSV.legacy');

    return;
}

if (!\class_exists(App_KernelEnvDebugContainer::class, false)) {
    \class_alias(\ContainerQXD6qSV\App_KernelEnvDebugContainer::class, App_KernelEnvDebugContainer::class, false);
}

return new \ContainerQXD6qSV\App_KernelEnvDebugContainer([
    'container.build_hash' => 'QXD6qSV',
    'container.build_id' => '43ae848c',
    'container.build_time' => 1608310014,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQXD6qSV');
