<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVnXtxqQ\App_KernelProDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVnXtxqQ/App_KernelProDebugContainer.php') {
    touch(__DIR__.'/ContainerVnXtxqQ.legacy');

    return;
}

if (!\class_exists(App_KernelProDebugContainer::class, false)) {
    \class_alias(\ContainerVnXtxqQ\App_KernelProDebugContainer::class, App_KernelProDebugContainer::class, false);
}

return new \ContainerVnXtxqQ\App_KernelProDebugContainer([
    'container.build_hash' => 'VnXtxqQ',
    'container.build_id' => '28fa9d18',
    'container.build_time' => 1608674680,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVnXtxqQ');
