<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAuMXSG7\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAuMXSG7/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAuMXSG7.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAuMXSG7\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerAuMXSG7\App_KernelProdContainer([
    'container.build_hash' => 'AuMXSG7',
    'container.build_id' => 'fa81546c',
    'container.build_time' => 1608674463,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAuMXSG7');
