<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA6gpc8r\App_KernelGhujDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA6gpc8r/App_KernelGhujDebugContainer.php') {
    touch(__DIR__.'/ContainerA6gpc8r.legacy');

    return;
}

if (!\class_exists(App_KernelGhujDebugContainer::class, false)) {
    \class_alias(\ContainerA6gpc8r\App_KernelGhujDebugContainer::class, App_KernelGhujDebugContainer::class, false);
}

return new \ContainerA6gpc8r\App_KernelGhujDebugContainer([
    'container.build_hash' => 'A6gpc8r',
    'container.build_id' => 'c722a97c',
    'container.build_time' => 1608310080,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA6gpc8r');
